### ISSUE TITLE
Use of the site code

### ISSUE THREAD

**Issue by IHARNAZAROV** [marslanwajid/SignupLogin#1]
Hi.
My name is Igor Nazarov. I am the developer of the anzhelika.by website. The source code is https://github.com/IHARNAZAROV/real-estate-portfolio
I see that you have created a copy of my site for your own purposes. I am glad that I have written a site that you can use and that will be informative and useful.
However, as an author and developer, I find it unpleasant that the footer of your site says “Made by marslanwajid- pixelcodewizard”
Although my site does not fall under licensing and intellectual property, this entry causes me some inconvenience. Could you please remove it. And also please remove the advertising site metrics counters. This is my only request.
Sincerely, Igor Nazarov

**Comment by marslanwajid** [comment]
Hey!

Sorry for the inconvenience! Sure I will remove it, And accept my apologies
for the inconvenience.

The site you make is soo good and fabulous, I really liked it and my
friend, for whom I customizes it also!

Regards
